### ISSUE TITLE
Does it work with XPS 15 too? Any binaries?

### ISSUE THREAD

**Issue by lastmetroid** [424778940z/dell-fan-utility#1]
Hello!

sorry to use the ticket for this, but you have no contact info on your site. Does your tool also maybe work with the Dell XPS 15 2017 or 2018? Can you maybe provide a compiled binary too? Thank you very much!

**Comment by 424778940z** [comment]
I tested this app on Dell M4600 (release around 2011), in theory it should work with other dell laptops (since the method was discovered around 2001), however there is no promises
[test.zip](https://github.com/424778940z/dell-fan-utility/files/2135100/test.zip)

**Comment by lastmetroid** [comment]
Hey @424778940z I wanted to give this another test on my XPS 9570. I am a bit unsure because of using pre build exe or drivers. How come the exe file is 16MB in size for such a tiny program?

**Comment by 424778940z** [comment]
> How come the exe file is 16MB in size for such a tiny program?

that't because you don't know Qt
